# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-13 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='invitation_code',
            field=models.CharField(default=1, max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='parent_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.User', to_field='invitation_code'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
