# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-14 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181213_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invitation_code',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
